export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_Fail'
export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_OUT = 'LOGIN_OUT'
export const LOAD_PROFILE = 'LOAD_PROFILE'